### ISSUE TITLE
Website Broken

### ISSUE THREAD

**Issue by ghost** [nexxydev/nexxydev#1]
![image](https://user-images.githubusercontent.com/63425900/140623934-c7a0f0ba-2a64-4135-899f-881cdf17e9ec.png)

**Comment by narashini** [comment]
Where is this? I only use "drafti.sh" on my dev DNS servers..

**Comment by ghost** [comment]
It was listed on your github profile.

> Where is this? I only use "drafti.sh" on my dev DNS servers..

**Comment by narashini** [comment]
> 

wait what?! i cant find it on my profile?

**Comment by ghost** [comment]
It was on your profile. At any rate the website "nexxydev.com" doesn't work and that _is_ on your profile.

> > 
> 
> wait what?! i cant find it on my profile?

**Comment by narashini** [comment]
> 

its listed as it is: "nexxydev.com (no workies)".
I am closing this as resolved because i do not feel this conversation needs to continue.
Cheers @Shayshon.

**Comment by ghost** [comment]
Wow. That was pretty aggressive. I'll be sure not to tell you when something is broken next time.

Cheers @nexxydev

**Comment by narashini** [comment]
Brought a domain and this is now marked as resolved, not sure how but thaught i would add that here.
